name: "Validate Infrastructure Changes"

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  TF_VERSION: "1.5.0"

jobs:
  validate:
    name: "Terraform Validate"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform Init with Backend
        run: |
          echo "🔧 Initializing Terraform with S3 backend..."
          terraform init \
            -backend-config="bucket=tech-challenge-fiap-terraform-state-2025" \
            -backend-config="key=infrastructure/terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="encrypt=true" \
            -backend-config="dynamodb_table=tech-challenge-fiap-terraform-locks"
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="aws_region=${{ vars.AWS_REGION }}" \
            -detailed-exitcode
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
        continue-on-error: true

      - name: Comment Plan Results
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const fs = require('fs');
            const planOutput = fs.readFileSync('${{ github.workspace }}/terraform-plan.txt', 'utf8');
            
            const comment = `## 🔍 Terraform Plan Results
            
            <details>
            <summary>Click to see the plan output</summary>
            
            \`\`\`
            ${planOutput}
            \`\`\`
            
            </details>
            
            **Note:** This is a preview of infrastructure changes. The actual deployment will happen when this PR is merged to main.`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            }); 